name: sportzone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: 4.6.6
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  intl: ^0.19.0
  phosphor_flutter: ^2.0.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Helvetica 35
      fonts:
        - asset: assets/fonts/Helvetica 35 Thin.ttf
    - family: Helvetica 45
      fonts:
        - asset: assets/fonts/Helvetica 45 Light.ttf
    - family: Helvetica 55
      fonts:
        - asset: assets/fonts/Helvetica 55 Roman.ttf
    - family: Helvetica 65
      fonts:
        - asset: assets/fonts/Helvetica 65 Medium.ttf
